version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    network_mode: bridge
    container_name: postgres
    environment:
      POSTGRES_DB: locacar
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
