INSERT INTO marcas(nome, created_at) VALUES
('FIAT', CURRENT_TIMESTAMP),
('VOLKSWAGEN', CURRENT_TIMESTAMP),
('BMW', CURRENT_TIMESTAMP),
('NISSAN', CURRENT_TIMESTAMP),
('TOYOTA', CURRENT_TIMESTAMP),
('HYUNDAI', CURRENT_TIMESTAMP),
('RENAULT', CURRENT_TIMESTAMP),
('MITSUBISHI', CURRENT_TIMESTAMP),
('HONDA', CURRENT_TIMESTAMP),
('FORD', CURRENT_TIMESTAMP);